<a href="https://colab.research.google.com/github/Ezer08/Job-Data-Cleaning-and-Transformation-for-Analysis/blob/main/Data_Cleaning_Project(Data__Science_JOB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files

# Step 1: Upload the file
uploaded = files.upload()

Saving Uncleaned_DS_jobs.csv to Uncleaned_DS_jobs.csv

In [ ]:
df= pd.read_csv('Uncleaned_DS_jobs.csv', sep=',')
df.head(5)

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [ ]:
df.shape

(672, 15)

In [ ]:
df.columns

Index(['index', 'Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors'],
      dtype='object')

In [ ]:
df.dtypes

index                  int64
Job Title             object
Salary Estimate       object
Job Description       object
Rating               float64
Company Name          object
Location              object
Headquarters          object
Size                  object
Founded                int64
Type of ownership     object
Industry              object
Sector                object
Revenue               object
Competitors           object
dtype: object

In [ ]:
#check missing value
df.isnull().sum()

index                0
Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         0
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
dtype: int64

In [ ]:
#check dupicates
df.duplicated().sum()

0

**Drop the 'index' column**

In [ ]:
dfc=df.copy()

In [ ]:
# Drop the 'index' column
dfc= dfc.drop(columns=['index'])

# Verify that the column has been removed
print(dfc.columns)

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors'],
      dtype='object')

**Extract from Salary Estimate: Minimum, Maximum, and Average Salary**

In [ ]:
# Remove unnecessary characters like 'K', '$', and 'Glassdoor est.' in dfc
dfc['Salary Estimate'] = dfc['Salary Estimate'].str.replace('K', '').str.replace('$', '').str.replace('(Glassdoor est.)', '').str.strip()

# Split the salary range into two columns in dfc
dfc[['Salary Min', 'Salary Max']] = dfc['Salary Estimate'].str.split('-', expand=True)

In [ ]:
dfc.head(5)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Min,Salary Max
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",137,171
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,137,171
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,137,171
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",137,171
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",137,171

In [ ]:
dfc.dtypes

Job Title             object
Salary Estimate       object
Job Description       object
Rating               float64
Company Name          object
Location              object
Headquarters          object
Size                  object
Founded                int64
Type of ownership     object
Industry              object
Sector                object
Revenue               object
Competitors           object
Salary Min            object
Salary Max            object
dtype: object

In [ ]:
# Convert Salary Min and Salary Max to integers if needed
# Extract numeric part using regex
# Ensure the columns are treated as strings first
dfc['Salary Min'] = dfc['Salary Min'].astype(str).str.extract('(\d+)').astype(int)
dfc['Salary Max'] = dfc['Salary Max'].astype(str).str.extract('(\d+)').astype(int)

# Check the updated DataFrame to ensure everything looks correct
print(dfc[['Salary Min', 'Salary Max']])

     Salary Min  Salary Max
0           137         171
1           137         171
2           137         171
3           137         171
4           137         171
..          ...         ...
667         105         167
668         105         167
669         105         167
670         105         167
671         105         167

[672 rows x 2 columns]

In [ ]:
print(dfc.dtypes)

Job Title             object
Salary Estimate       object
Job Description       object
Rating               float64
Company Name          object
Location              object
Headquarters          object
Size                  object
Founded                int64
Type of ownership     object
Industry              object
Sector                object
Revenue               object
Competitors           object
Salary Min             int64
Salary Max             int64
dtype: object

In [ ]:
# Rename the 'Salary Min' and 'Salary Max' columns
dfc = dfc.rename(columns={'Salary Min': 'Salary Min estimated', 'Salary Max': 'Salary Max estimated'})

# Calculate the average salary and create a new column called 'average salary estimated'
dfc['average salary estimated'] = (dfc['Salary Min estimated'] + dfc['Salary Max estimated']) / 2

# Check the updated DataFrame
print(dfc[['Salary Min estimated', 'Salary Max estimated', 'average salary estimated']])

     Salary Min estimated  Salary Max estimated  average salary estimated
0                     137                   171                     154.0
1                     137                   171                     154.0
2                     137                   171                     154.0
3                     137                   171                     154.0
4                     137                   171                     154.0
..                    ...                   ...                       ...
667                   105                   167                     136.0
668                   105                   167                     136.0
669                   105                   167                     136.0
670                   105                   167                     136.0
671                   105                   167                     136.0

[672 rows x 3 columns]

**Clean the Job Description column**

In [ ]:
# Clean the Job Description column by removing newline characters and extra whitespace
dfc['Job Description'] = dfc['Job Description'].str.replace('\n', ' ').str.strip()

# Check the updated Job Description column
print(dfc['Job Description'])

0      Description  The Senior Data Scientist is resp...
1      Secure our Nation, Ignite your Future  Join th...
2      Overview   Analysis Group is one of the larges...
3      JOB DESCRIPTION:  Do you have a passion for Da...
4      Data Scientist Affinity Solutions / Marketing ...
                             ...
667    Summary  We’re looking for a data scientist to...
668    Job Description Become a thought leader within...
669    Join a thriving company that is changing the w...
670    100 Remote Opportunity As an AINLP Data Scient...
671    Description  The Data Scientist will be part o...
Name: Job Description, Length: 672, dtype: object

**Clean the Company Name**

In [ ]:
# Clean the Company Name column by removing the rating
dfc['Company Name'] = dfc['Company Name'].str.split('\n').str[0]

# Check the updated Company Name column
print(dfc['Company Name'])

0               Healthfirst
1                   ManTech
2            Analysis Group
3                   INFICON
4        Affinity Solutions
               ...
667                TRANZACT
668                    JKGT
669              AccessHope
670    ChaTeck Incorporated
671           1-800-Flowers
Name: Company Name, Length: 672, dtype: object

**Extract the state from the Location column**

In [ ]:
# Extract the state from the Location column
dfc['State'] = dfc['Location'].str.split(',').str[-1].str.strip()

# Check the updated DataFrame
print(dfc[['Location', 'State']])

              Location State
0         New York, NY    NY
1        Chantilly, VA    VA
2           Boston, MA    MA
3           Newton, MA    MA
4         New York, NY    NY
..                 ...   ...
667       Fort Lee, NJ    NJ
668  San Francisco, CA    CA
669      Irwindale, CA    CA
670  San Francisco, CA    CA
671       New York, NY    NY

[672 rows x 2 columns]

In [ ]:
# Get the unique states from the State column
unique_states = dfc['State'].unique()

# Print the list of unique states
print(unique_states)

['NY' 'VA' 'MA' 'CA' 'IL' 'MO' 'WA' 'DC' 'Remote' 'TN' 'TX' 'PA' 'AZ' 'WI'
 'GA' 'FL' 'United States' 'NE' 'KS' 'NH' 'NJ' 'LA' 'OH' 'IN' 'MD' 'CO'
 'Utah' 'New Jersey' 'UT' 'OR' 'MI' 'SC' 'MS' 'AL' 'RI' 'IA' 'MN' 'OK'
 'CT' 'NC' 'Texas' 'DE' 'California' 'WV']

In [ ]:
# Create a dictionary for state abbreviations and their corresponding full names
state_dict = {
    'NY': 'New York',
    'VA': 'Virginia',
    'MA': 'Massachusetts',
    'CA': 'California',
    'IL': 'Illinois',
    'MO': 'Missouri',
    'WA': 'Washington',
    'DC': 'District of Columbia',
    'Remote': 'Remote',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'PA': 'Pennsylvania',
    'AZ': 'Arizona',
    'WI': 'Wisconsin',
    'GA': 'Georgia',
    'FL': 'Florida',
    'United States': 'United States',
    'NE': 'Nebraska',
    'KS': 'Kansas',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'LA': 'Louisiana',
    'OH': 'Ohio',
    'IN': 'Indiana',
    'MD': 'Maryland',
    'CO': 'Colorado',
    'Utah': 'Utah',
    'New Jersey': 'New Jersey',
    'UT': 'Utah',
    'OR': 'Oregon',
    'MI': 'Michigan',
    'SC': 'South Carolina',
    'MS': 'Mississippi',
    'AL': 'Alabama',
    'RI': 'Rhode Island',
    'IA': 'Iowa',
    'MN': 'Minnesota',
    'OK': 'Oklahoma',
    'CT': 'Connecticut',
    'NC': 'North Carolina',
    'Texas': 'Texas',
    'DE': 'Delaware',
    'California': 'California',
    'WV': 'West Virginia'
}

# Replace state abbreviations in the State column with full names
dfc['State'] = dfc['State'].replace(state_dict)

# Check the updated State column
print(dfc[['State']])

             State
0         New York
1         Virginia
2    Massachusetts
3    Massachusetts
4         New York
..             ...
667     New Jersey
668     California
669     California
670     California
671       New York

[672 rows x 1 columns]

**Clean column Size**

In [ ]:
# Rename the Size column to Number of Employees
dfc.rename(columns={'Size': 'Number of Employees'}, inplace=True)

# Check the updated DataFrame
print(dfc[['Number of Employees']])

         Number of Employees
0     1001 to 5000 employees
1    5001 to 10000 employees
2     1001 to 5000 employees
3      501 to 1000 employees
4        51 to 200 employees
..                       ...
667   1001 to 5000 employees
668                       -1
669                       -1
670        1 to 50 employees
671   1001 to 5000 employees

[672 rows x 1 columns]

In [ ]:
# Function to convert number of employees to a list of integers
def convert_employees(emp_str):
    # Check for 'Unknown' and handle it
    if 'Unknown' in emp_str:
        return None  # or return [] if you prefer an empty list

    # Remove ' employees' and handle cases with '+' or any other characters
    emp_str = emp_str.replace(' employees', '').replace('+', '').strip()

    # Split the string on ' to ' and convert to integers
    if ' to ' in emp_str:
        return [int(x) for x in emp_str.split(' to ')]
    else:
        # Handle cases with a single number
        return [int(emp_str), int(emp_str)]

# Apply the conversion function to the Number of Employees column
dfc['Number of Employees'] = dfc['Number of Employees'].apply(convert_employees)

# Check the updated Number of Employees column
print(dfc[['Number of Employees']])

    Number of Employees
0          [1001, 5000]
1         [5001, 10000]
2          [1001, 5000]
3           [501, 1000]
4             [51, 200]
..                  ...
667        [1001, 5000]
668            [-1, -1]
669            [-1, -1]
670             [1, 50]
671        [1001, 5000]

[672 rows x 1 columns]

In [ ]:
# Function to convert revenue to a list of strings in the desired format
def convert_revenue(revenue_str):
    # Remove the '(USD)' part and any leading/trailing whitespace
    revenue_str = revenue_str.replace(' (USD)', '').strip()

    # Check for 'Unknown' and handle it
    if 'Unknown' in revenue_str:
        return None  # or return [] if you prefer an empty list

    # Split the string on ' to ' and clean each part
    if ' to ' in revenue_str:
        # Create a list and ensure it maintains the '$' sign and ' billion'
        return [part.strip() + ' billion' for part in revenue_str.split(' to ')]
    else:
        # Handle cases with a single value
        return [revenue_str.strip() + ' billion', revenue_str.strip() + ' billion']

# Apply the conversion function to the Revenue column
dfc['Revenue'] = dfc['Revenue'].apply(convert_revenue)

# Rename the Revenue column to Revenue Range
dfc.rename(columns={'Revenue': 'Revenue Range'}, inplace=True)

# Check the updated DataFrame
print(dfc[['Revenue Range']])

                            Revenue Range
0                                    None
1        [$1 billion, $2 billion billion]
2    [$100 billion, $500 million billion]
3    [$100 billion, $500 million billion]
4                                    None
..                                    ...
667                                  None
668              [-1 billion, -1 billion]
669              [-1 billion, -1 billion]
670      [$1 billion, $5 million billion]
671      [$1 billion, $2 billion billion]

[672 rows x 1 columns]

In [ ]:
# Replace None values in the Revenue Range column with 'Unknown'
dfc['Revenue Range'] = dfc['Revenue Range'].apply(lambda x: x if x is not None else 'Unknown')

# Check the updated Revenue Range column
print(dfc[['Revenue Range']])

                            Revenue Range
0                                 Unknown
1        [$1 billion, $2 billion billion]
2    [$100 billion, $500 million billion]
3    [$100 billion, $500 million billion]
4                                 Unknown
..                                    ...
667                               Unknown
668              [-1 billion, -1 billion]
669              [-1 billion, -1 billion]
670      [$1 billion, $5 million billion]
671      [$1 billion, $2 billion billion]

[672 rows x 1 columns]

In [ ]:
dfc.head(5)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Number of Employees,Founded,Type of ownership,Industry,Sector,Revenue Range,Competitors,Salary Min estimated,Salary Max estimated,average salary estimated,State
0,Sr Data Scientist,137-171,Description The Senior Data Scientist is resp...,3.1,Healthfirst,"New York, NY","New York, NY","[1001, 5000]",1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown,"EmblemHealth, UnitedHealth Group, Aetna",137,171,154.0,New York
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future Join th...",4.2,ManTech,"Chantilly, VA","Herndon, VA","[5001, 10000]",1968,Company - Public,Research & Development,Business Services,"[$1 billion, $2 billion billion]",-1,137,171,154.0,Virginia
2,Data Scientist,137-171,Overview Analysis Group is one of the larges...,3.8,Analysis Group,"Boston, MA","Boston, MA","[1001, 5000]",1981,Private Practice / Firm,Consulting,Business Services,"[$100 billion, $500 million billion]",-1,137,171,154.0,Massachusetts
3,Data Scientist,137-171,JOB DESCRIPTION: Do you have a passion for Da...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland","[501, 1000]",2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,"[$100 billion, $500 million billion]","MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",137,171,154.0,Massachusetts
4,Data Scientist,137-171,Data Scientist Affinity Solutions / Marketing ...,2.9,Affinity Solutions,"New York, NY","New York, NY","[51, 200]",1998,Company - Private,Advertising & Marketing,Business Services,Unknown,"Commerce Signals, Cardlytics, Yodlee",137,171,154.0,New York

In [ ]:
# Define the desired order of columns
desired_order = [
    'Job Title',
    'Salary Estimate',
    'Salary Min estimated',
    'Salary Max estimated',
    'average salary estimated',
    'Job Description',
    'Rating',
    'Company Name',
    'Location',
    'State',
    'Headquarters',
    'Number of Employees',
    'Founded',
    'Type of ownership',
    'Industry',
    'Sector',
    'Revenue Range',
    'Competitors',
]

# Reorder the columns
dfc = dfc[desired_order]

# Check the updated DataFrame to confirm the order
dfc.head(5)

,Job Title,Salary Estimate,Salary Min estimated,Salary Max estimated,average salary estimated,Job Description,Rating,Company Name,Location,State,Headquarters,Number of Employees,Founded,Type of ownership,Industry,Sector,Revenue Range,Competitors
0,Sr Data Scientist,137-171,137,171,154.0,Description The Senior Data Scientist is resp...,3.1,Healthfirst,"New York, NY",New York,"New York, NY","[1001, 5000]",1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown,"EmblemHealth, UnitedHealth Group, Aetna"
1,Data Scientist,137-171,137,171,154.0,"Secure our Nation, Ignite your Future Join th...",4.2,ManTech,"Chantilly, VA",Virginia,"Herndon, VA","[5001, 10000]",1968,Company - Public,Research & Development,Business Services,"[$1 billion, $2 billion billion]",-1
2,Data Scientist,137-171,137,171,154.0,Overview Analysis Group is one of the larges...,3.8,Analysis Group,"Boston, MA",Massachusetts,"Boston, MA","[1001, 5000]",1981,Private Practice / Firm,Consulting,Business Services,"[$100 billion, $500 million billion]",-1
3,Data Scientist,137-171,137,171,154.0,JOB DESCRIPTION: Do you have a passion for Da...,3.5,INFICON,"Newton, MA",Massachusetts,"Bad Ragaz, Switzerland","[501, 1000]",2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,"[$100 billion, $500 million billion]","MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,Data Scientist,137-171,137,171,154.0,Data Scientist Affinity Solutions / Marketing ...,2.9,Affinity Solutions,"New York, NY",New York,"New York, NY","[51, 200]",1998,Company - Private,Advertising & Marketing,Business Services,Unknown,"Commerce Signals, Cardlytics, Yodlee"

In [ ]:
# Rename the specified columns to indicate that the values are in thousands (K)
dfc.rename(columns={
    'Salary Min estimated': 'Salary Min (K)',
    'Salary Max estimated': 'Salary Max (K)',
    'average salary estimated': 'Average Salary (K)',
}, inplace=True)

# Check the updated DataFrame to confirm the new column names
dfc.head(5)

,Job Title,Salary Estimate,Salary Min (K),Salary Max (K),Average Salary (K),Job Description,Rating,Company Name,Location,State,Headquarters,Number of Employees,Founded,Type of ownership,Industry,Sector,Revenue Range,Competitors
0,Sr Data Scientist,137-171,137,171,154.0,Description The Senior Data Scientist is resp...,3.1,Healthfirst,"New York, NY",New York,"New York, NY","[1001, 5000]",1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown,"EmblemHealth, UnitedHealth Group, Aetna"
1,Data Scientist,137-171,137,171,154.0,"Secure our Nation, Ignite your Future Join th...",4.2,ManTech,"Chantilly, VA",Virginia,"Herndon, VA","[5001, 10000]",1968,Company - Public,Research & Development,Business Services,"[$1 billion, $2 billion billion]",-1
2,Data Scientist,137-171,137,171,154.0,Overview Analysis Group is one of the larges...,3.8,Analysis Group,"Boston, MA",Massachusetts,"Boston, MA","[1001, 5000]",1981,Private Practice / Firm,Consulting,Business Services,"[$100 billion, $500 million billion]",-1
3,Data Scientist,137-171,137,171,154.0,JOB DESCRIPTION: Do you have a passion for Da...,3.5,INFICON,"Newton, MA",Massachusetts,"Bad Ragaz, Switzerland","[501, 1000]",2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,"[$100 billion, $500 million billion]","MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,Data Scientist,137-171,137,171,154.0,Data Scientist Affinity Solutions / Marketing ...,2.9,Affinity Solutions,"New York, NY",New York,"New York, NY","[51, 200]",1998,Company - Private,Advertising & Marketing,Business Services,Unknown,"Commerce Signals, Cardlytics, Yodlee"

In [ ]:
# Drop the Salary Estimate column
dfc.drop(columns=['Salary Estimate'], inplace=True)

KeyError: "['Salary Estimate'] not found in axis"

In [ ]:

# Check the updated DataFrame to confirm the column has been dropped
dfc.head(5)

,Job Title,Salary Min (K),Salary Max (K),Average Salary (K),Job Description,Rating,Company Name,Location,State,Headquarters,Number of Employees,Founded,Type of ownership,Industry,Sector,Revenue Range,Competitors
0,Sr Data Scientist,137,171,154.0,Description The Senior Data Scientist is resp...,3.1,Healthfirst,"New York, NY",New York,"New York, NY","[1001, 5000]",1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown,"EmblemHealth, UnitedHealth Group, Aetna"
1,Data Scientist,137,171,154.0,"Secure our Nation, Ignite your Future Join th...",4.2,ManTech,"Chantilly, VA",Virginia,"Herndon, VA","[5001, 10000]",1968,Company - Public,Research & Development,Business Services,"[$1 billion, $2 billion billion]",-1
2,Data Scientist,137,171,154.0,Overview Analysis Group is one of the larges...,3.8,Analysis Group,"Boston, MA",Massachusetts,"Boston, MA","[1001, 5000]",1981,Private Practice / Firm,Consulting,Business Services,"[$100 billion, $500 million billion]",-1
3,Data Scientist,137,171,154.0,JOB DESCRIPTION: Do you have a passion for Da...,3.5,INFICON,"Newton, MA",Massachusetts,"Bad Ragaz, Switzerland","[501, 1000]",2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,"[$100 billion, $500 million billion]","MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,Data Scientist,137,171,154.0,Data Scientist Affinity Solutions / Marketing ...,2.9,Affinity Solutions,"New York, NY",New York,"New York, NY","[51, 200]",1998,Company - Private,Advertising & Marketing,Business Services,Unknown,"Commerce Signals, Cardlytics, Yodlee"